apiVersion: v1
kind: ConfigMap
metadata:
  name: journal-config
  namespace: journal-app
data:
  SPRING_APPLICATION_NAME: journal-app

  # Mongo
  SPRING_DATA_MONGODB_URI: mongodb://admin:password123@journal-mongodb-0.journal-mongodb.journal-app.svc.cluster.local:27017/journalDB?authSource=admin

  # Redis
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_GROUP: weekly-sentiment-group

  # Server
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: /journal

  # Weather
  WEATHER_API_URL: http://api.weatherstack.com/current?access_key=YOUR_ACCESS_KEYquery=CITY

