apiVersion: v1
kind: Service
metadata:
  name: journal-service
  namespace: journal-app
spec:
  type: NodePort
  selector:
    app: journal-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

